#!/usr/bin/env python3
"""Generate main-acm.tex (ACM acmsmall journal format) from main-arxiv.tex.

The arXiv file is the canonical source. This script swaps the preamble and
title block, leaves the body untouched, and switches the bibliography style.

    python3 make-acm.py            # identified build
    python3 make-acm.py --anon     # anonymous build for double-anonymous review

Optional: --journal "Full Journal Name" --journal-short "Abbrev. Name" overrides
the running-header strings, for a journal newer than the installed acmart.
Submission-time material (cover letters, anonymized builds) is git-ignored.
"""
import re, sys

ANON = '--anon' in sys.argv

def _opt(flag):
    return sys.argv[sys.argv.index(flag) + 1] if flag in sys.argv else None

journal_override = ''
if _opt('--journal'):
    journal_override = ('\\makeatletter\n'
                        '\\def\\@journalName{' + _opt('--journal') + '}\n'
                        '\\def\\@journalNameShort{' + (_opt('--journal-short') or _opt('--journal')) + '}\n'
                        '\\def\\@permissionCodeOne{}\n'
                        '\\makeatother\n')
src = open('main-arxiv.tex').read()

body_start = src.index(r'\begin{document}')
body = src[body_start + len(r'\begin{document}'):]

# --- title block --------------------------------------------------------
title = re.search(r'\\title\{(.*?)\}\n', src, re.S).group(1)
abstract = re.search(r'\\begin\{abstract\}(.*?)\\end\{abstract\}', body, re.S).group(1)
keywords = re.search(r'\\keywords\{(.*?)\}', body).group(1).replace(r' \and ', ', ')

# strip the arXiv-style front matter from the body
body = body.replace(r'\maketitle', '', 1)
body = re.sub(r'\\begin\{abstract\}.*?\\end\{abstract\}\n*', '', body, count=1, flags=re.S)
body = re.sub(r'\\keywords\{.*?\}\n*', '', body, count=1)
body = body.replace(r'\bibliographystyle{plainnat}', r'\bibliographystyle{ACM-Reference-Format}')

# In anonymous builds, neutralise self-identifying text.
if ANON:
    body = body.replace(r'\url{https://github.com/NERVsystems/namespace-bounded-agents}, DOI: \href{https://doi.org/10.5281/zenodo.18419123}{10.5281/zenodo.18419123}',
                        'Repository URL and DOI withheld for anonymous review; artifacts will be provided to reviewers on request through the editor.')
    body = body.replace('deployed end-to-end in InferNode, a production derivative of Inferno OS',
                        'deployed end-to-end in a production derivative of Inferno OS')

opts = 'acmsmall,screen,review' + (',anonymous' if ANON else '')

preamble = r'''\documentclass[''' + opts + r''']{acmart}
%% Generated by make-acm.py from main-arxiv.tex -- edit the arXiv source, not this file.

\usepackage{listings}
\usepackage{tikz}
\usetikzlibrary{shapes,arrows,positioning}
\usepackage{booktabs}
\usepackage{adjustbox}
\def\UrlBreaks{\do\/\do-\do_\do.\do=\do?\do&\do\#}
\Urlmuskip=0mu plus 1mu

\lstset{
  basicstyle=\ttfamily\small,
  breaklines=true,
  frame=single,
  backgroundcolor=\color{gray!10}
}

\setcopyright{none}
\acmJournal{TOPS}
''' + journal_override + r'''\acmYear{2026}
\acmDOI{}
\acmISBN{}
\settopmatter{printacmref=false}
\renewcommand\footnotetextcopyrightpermission[1]{}

\begin{CCSXML}
<ccs2012>
<concept>
<concept_id>10002978.10003001.10003599</concept_id>
<concept_desc>Security and privacy~Operating systems security</concept_desc>
<concept_significance>500</concept_significance>
</concept>
<concept>
<concept_id>10002978.10002991.10002993</concept_id>
<concept_desc>Security and privacy~Access control</concept_desc>
<concept_significance>500</concept_significance>
</concept>
<concept>
<concept_id>10002978.10003022</concept_id>
<concept_desc>Security and privacy~Software and application security</concept_desc>
<concept_significance>300</concept_significance>
</concept>
<concept>
<concept_id>10010147.10010178</concept_id>
<concept_desc>Computing methodologies~Artificial intelligence</concept_desc>
<concept_significance>300</concept_significance>
</concept>
</ccs2012>
\end{CCSXML}
\ccsdesc[500]{Security and privacy~Operating systems security}
\ccsdesc[500]{Security and privacy~Access control}
\ccsdesc[300]{Security and privacy~Software and application security}
\ccsdesc[300]{Computing methodologies~Artificial intelligence}

\title[Namespace-Bounded Agents]{''' + title + r'''}

\author{Peter D. Finn}
\orcid{}%% TODO(author): ORCID iD
\email{pdf@nervsystems.com}
\affiliation{%
  \institution{King's College London}
  \city{London}
  \country{United Kingdom}
}
\affiliation{%
  \institution{NERV Systems}
  \country{USA}
}

\begin{abstract}''' + abstract + r'''\end{abstract}

\keywords{''' + keywords + r'''}

\begin{document}

\maketitle
'''

# --- split: appendix becomes a separate supplementary document ------------
main_body, appendix = body.split(r'\appendix', 1)
appendix = appendix.replace(r'\end{document}', '')
# Relocate marked blocks (%% BEGIN SUPP <title> ... %% END SUPP) into the supplement.
supp_extra = ''
for m in list(re.finditer(r'%% BEGIN SUPP ([^\n]*)\n(.*?)%% END SUPP\n', main_body, re.S)):
    title, block = m.group(1).strip(), m.group(2)
    block = block.replace(r'\subsubsection{', r'\subsection{')
    supp_extra += '\n' + r'\section{' + title + '}' + '\n' + block
    main_body = main_body.replace(m.group(0),
        'Tool-by-tool details---TLA+ configurations and invariants, the five SPIN models, and the CBMC harnesses---are given in the supplementary material (Appendix~B).\n\n')
appendix += supp_extra
main_body += '\n' + r'\end{document}' + '\n'
main_body = main_body.replace(r'\bibliography{references}',
    r'\bibliography{references}' + '\n\n'
    r'\section*{Artifact and Supplementary Material}' + '\n'
    r'All evaluation code, attack prompts, raw results, and verification artifacts are available in our open-source repository'
    + ('.' if ANON else r'.\footnote{\url{https://github.com/NERVsystems/namespace-bounded-agents}, DOI: \href{https://doi.org/10.5281/zenodo.18419123}{10.5281/zenodo.18419123}}')
    + r' The supplementary material (Appendix~A) gives the environment specification, model configuration (Table~\ref{tab:model-config}), attack corpus structure, pass/fail rubric, and the AgentDojo integration and run-provenance notes (Section~\ref{sec:agentdojo-integration}).' + '\n')
# cross-references from main text into the appendix need externaldocument
main_body = main_body.replace(r'\end{document}', r'\end{document}')
stem = 'main-acm-anon' if ANON else 'main-acm'
main_pre = preamble.replace(r'\begin{document}', r'\usepackage{xr}\externaldocument{' + stem + r'-supp}' + '\n' + r'\begin{document}')
open(stem + '.tex', 'w').write(main_pre + main_body)
supp_pre = preamble.replace(r'\begin{document}', r'\usepackage{xr}\externaldocument{' + stem + r'}' + '\n' + r'\begin{document}')
supp_pre = supp_pre.replace(r'\title[Namespace-Bounded Agents]{', r'\title[Namespace-Bounded Agents: Supplementary Material]{Supplementary Material for: ')
supp = supp_pre.replace(r'\begin{abstract}' + abstract + r'\end{abstract}', r'\begin{abstract}This supplement accompanies the main article and contains the evaluation artifacts: environment specification, reproducibility checklist, model configuration, attack corpus structure, pass/fail rubric, and AgentDojo integration notes.\end{abstract}')
supp += r'\appendix' + appendix + r'\bibliographystyle{ACM-Reference-Format}' + '\n' + r'\bibliography{references}' + '\n' + r'\end{document}' + '\n'
open(stem + '-supp.tex', 'w').write(supp)
print('wrote', stem + '.tex', 'and', stem + '-supp.tex')
